version: '3.8'

services:

  datahandler-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: datahandler
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000
    volumes:
      - .:/app
    restart: on-failure
    ports:
      - 8000:8000
    #    depends_on:
    #      - rabbitmq
    networks:
      - data-handler-network

  #  redis:
  #    image: redis:latest
  #    ports:
  #      - 6378:6379
  #    depends_on:
  #      - rabbitmq

  datahandler-celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: datahandler-celery-worker
    command: /start-celeryworker
    volumes:
      - .:/app
    #    depends_on:
    #      - rabbitmq
    networks:
      - data-handler-network

  datahandler-celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    image: datahandler-celery-beat
    command: /start-celerybeat
    depends_on:
      - datahandler-celery-worker
    #      - rabbitmq
    networks:
      - data-handler-network

networks:
  data-handler-network:
    external: true
